"""add is_selected to cart_items

Revision ID: 555df7455e61
Revises: d236c166170e
Create Date: 2026-03-02 19:43:00.442722

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "555df7455e61"
down_revision: Union[str, Sequence[str], None] = "d236c166170e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "cart_items",
        sa.Column("is_selected", sa.Boolean(), server_default="true", nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("cart_items", "is_selected")
    # ### end Alembic commands ###
