"""Change product_id type from UUID to Integer in cart_items

Revision ID: d236c166170e
Revises: 36ce6e3624d0
Create Date: 2026-02-24 13:31:16.509119

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d236c166170e"
down_revision: Union[str, Sequence[str], None] = "36ce6e3624d0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("cart_items", "product_id")
    op.add_column("cart_items", sa.Column("product_id", sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("cart_items", "product_id")
    op.add_column("cart_items", sa.Column("product_id", sa.UUID(), nullable=False))
    # ### end Alembic commands ###
